import { EventModel } from "./event-model";

export class CalendarDimensionModel {
  ID: number;
  Date: string;
  GregDate: string;
  GregKey: number;
  JalaliDate: string;
  HijriDate: string;
  HijriKey: number;
  YearKey: number;
  YearName: string;
  SeasonKey: number;
  SeasonName: string;
  MonthKey: number;
  MonthName: string;
  WeekOfYearKey: number;
  DayOfWeekKey: number;
  DayOfWeekName: string;
  DayKey: number;
  DayName: string;
  DayOfYearKey: number;
  JalaliAlphabetic: string;
  GregYearKey: number;
  GregSeasonKey: number;
  GregMonthKey: number;
  GregWeekKey: number;
  GregDayKey: number;
  GregSeasonName: string;
  GregSeasonNameFa: string;
  GregMonthName: string;
  GregMonthNameFa: string;
  SeasonIndex: number;
  MonthIndex: number;
  WeekIndex: number;
  DayIndex: number;
  WorkdayIndex: number;
  MidYear: number;
  MidSeason: number;
  MidMonth: number;
  IsHoliday: boolean;
  IsWorkDay: boolean;
  IsFirstOfYear: boolean;
  IsLastOfYear: boolean;
  IsFirstOfSeason: boolean;
  IsLastOfSeason: boolean;
  IsFirstOfMonth: boolean;
  IsLastOfMonth: boolean;
  IsFirstOfWeek: boolean;
  IsLastOfWeek: boolean;
  IsLeap: boolean;
  Identifier: string;
  Hash: string;
  Time: string;
  IsActive: boolean;
  Events: EventModel[];
  StringJalaliDateTime?: string;
  constructor(init?: Partial<CalendarDimensionModel>) {
    this.ID = init?.ID || 0;
    this.Date = init?.Date || '';
    this.GregDate = init?.GregDate || '';
    this.GregKey = init?.GregKey || 0;
    this.JalaliDate = init?.JalaliDate || '';
    this.HijriDate = init?.HijriDate || '';
    this.HijriKey = init?.HijriKey || 0;
    this.YearKey = init?.YearKey || 0;
    this.YearName = init?.YearName || '';
    this.SeasonKey = init?.SeasonKey || 0;
    this.SeasonName = init?.SeasonName || '';
    this.MonthKey = init?.MonthKey || 0;
    this.MonthName = init?.MonthName || '';
    this.WeekOfYearKey = init?.WeekOfYearKey || 0;
    this.DayOfWeekKey = init?.DayOfWeekKey || 0;
    this.DayOfWeekName = init?.DayOfWeekName || '';
    this.DayKey = init?.DayKey || 0;
    this.DayName = init?.DayName || '';
    this.DayOfYearKey = init?.DayOfYearKey || 0;
    this.JalaliAlphabetic = init?.JalaliAlphabetic || '';
    this.GregYearKey = init?.GregYearKey || 0;
    this.GregSeasonKey = init?.GregSeasonKey || 0;
    this.GregMonthKey = init?.GregMonthKey || 0;
    this.GregWeekKey = init?.GregWeekKey || 0;
    this.GregDayKey = init?.GregDayKey || 0;
    this.GregSeasonName = init?.GregSeasonName || '';
    this.GregSeasonNameFa = init?.GregSeasonNameFa || '';
    this.GregMonthName = init?.GregMonthName || '';
    this.GregMonthNameFa = init?.GregMonthNameFa || '';
    this.SeasonIndex = init?.SeasonIndex || 0;
    this.MonthIndex = init?.MonthIndex || 0;
    this.WeekIndex = init?.WeekIndex || 0;
    this.DayIndex = init?.DayIndex || 0;
    this.WorkdayIndex = init?.WorkdayIndex || 0;
    this.MidYear = init?.MidYear || 0;
    this.MidSeason = init?.MidSeason || 0;
    this.MidMonth = init?.MidMonth || 0;
    this.IsHoliday = init?.IsHoliday || true;
    this.IsWorkDay = init?.IsWorkDay || true;
    this.IsFirstOfYear = init?.IsFirstOfYear || true;
    this.IsLastOfYear = init?.IsLastOfYear || true;
    this.IsFirstOfSeason = init?.IsFirstOfSeason || true;
    this.IsLastOfSeason = init?.IsLastOfSeason || true;
    this.IsFirstOfMonth = init?.IsFirstOfMonth || true;
    this.IsLastOfMonth = init?.IsLastOfMonth || true;
    this.IsFirstOfWeek = init?.IsFirstOfWeek || true;
    this.IsLastOfWeek = init?.IsLastOfWeek || true;
    this.IsLeap = init?.IsLeap || true;
    this.Identifier = init?.Identifier || '';
    this.Hash = init?.Hash || '';
    this.Time = init?.Time || '';
    this.IsActive = init?.IsActive || true;
    this.Events = init?.Events || [];
    this.StringJalaliDateTime = init?.StringJalaliDateTime || '';
  }
}
